company_task_manager/urls.py
from django.contrib import admin
from django.urls import path, include

from task_manager.views import RegisterView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path("", include("task_manager.urls", namespace="task_manager")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/register/", RegisterView.as_view(), name="register"),
]

task_manager/urls.py
from django.urls import path

from task_manager.views import (
    WorkerListView,
    PositionListView,
    TaskTypeListView,
    TaskListView,
    TaskCreateView,
    TaskUpdateView,
    IndexView,
)

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("workers/", WorkerListView.as_view(), name="worker-list"),
    path("positions/", PositionListView.as_view(), name="position-list"),
    path("task_types/", TaskTypeListView.as_view(), name="task-type-list"),
    path("tasks/", TaskListView.as_view(), name="task-list"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path(
        "tasks/<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update",
    ),
]

app_name = "task_manager"

task_manager/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class Position(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Worker(AbstractUser):
    position = models.ForeignKey(
        Position,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="workers",
    )

    def __str__(self):
        return f"{self.username} ({self.position})"


class TaskType(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Task(models.Model):
    PRIORITIES = [
        ("U", "Urgent"),
        ("H", "High"),
        ("M", "Medium"),
        ("L", "Low"),
    ]

    name = models.CharField(max_length=255)
    description = models.TextField()
    deadline = models.DateField()
    is_completed = models.BooleanField(default=False)
    priority = models.CharField(max_length=1, choices=PRIORITIES, default="M")
    task_type = models.ForeignKey(
        TaskType, on_delete=models.SET_NULL, null=True, related_name="tasks"
    )
    assignees = models.ManyToManyField(Worker, related_name="tasks_assigned")
    assignor = models.ForeignKey(
        Worker,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="tasks_created"
    )

    def __str__(self):
        return self.name

task_manager/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.forms import CheckboxSelectMultiple

from task_manager.models import Task, Worker, Position

User = get_user_model()


class RegisterForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.required = True

    class Meta:
        model = User
        fields = [
            "username",
            "password1",
            "password2",
            "first_name",
            "last_name",
            "email",
            "position",
        ]


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = "__all__"
        exclude = ("assignor",)

        widgets = {
            "deadline": forms.DateInput(attrs={"type": "date"}),
            "description": forms.Textarea(attrs={"rows": 2}),
            "assignees": CheckboxSelectMultiple(),
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user")
        super(TaskForm, self).__init__(*args, **kwargs)
        self.fields["assignees"].queryset = Worker.objects.filter(
            position=user.position
        )


class TaskNameSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search by task name..."}
        ),
    )

task_manager/views.py
import datetime

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic import TemplateView

from task_manager.forms import TaskForm, RegisterForm, TaskNameSearchForm
from task_manager.models import Worker, Position, TaskType, Task


class IndexView(TemplateView):
    template_name = "index.html"


class WorkerListView(LoginRequiredMixin, generic.ListView):
    model = Worker
    template_name = "worker_list.html"


class PositionListView(LoginRequiredMixin, generic.ListView):
    model = Position
    template_name = "position_list.html"


class TaskTypeListView(LoginRequiredMixin, generic.ListView):
    model = TaskType
    template_name = "task_type_list.html"


class TaskListView(LoginRequiredMixin, generic.ListView):
    model = Task
    template_name = "task_list.html"

    def get_queryset(self):
        current_user = self.request.user
        queryset = Task.objects.filter(
            Q(assignor=current_user) | Q(assignees=current_user)
        ).order_by('is_completed', 'deadline').distinct()
        form = TaskNameSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])

        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TaskListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = TaskNameSearchForm(initial={"name": name})
        context["today"] = datetime.date.today()

        return context


class TaskCreateView(LoginRequiredMixin, generic.CreateView):
    model = Task
    form_class = TaskForm
    template_name = "task_form.html"
    success_url = reverse_lazy("task_manager:task-list")

    def form_valid(self, form):
        form.instance.assignor = self.request.user
        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super(TaskCreateView, self).get_form_kwargs()
        kwargs.update({"user": self.request.user})
        return kwargs


class TaskUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Task
    form_class = TaskForm
    template_name = "task_form.html"
    success_url = reverse_lazy("task_manager:task-list")

    def get_form_kwargs(self):
        kwargs = super(TaskUpdateView, self).get_form_kwargs()
        kwargs.update({"user": self.request.user})
        return kwargs


class RegisterView(generic.CreateView):
    form_class = RegisterForm
    success_url = reverse_lazy("login")
    template_name = "registration/register.html"

    def dispatch(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect("task_manager:index")
        return super().dispatch(*args, **kwargs)

task_manager/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% block title %}
    <title>Task Manager</title>
  {% endblock %}
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
</head>
<body>

<div class="container-fluid">
  <div class="row vh-100">
    <div class="col-sm-2 bg-light  p-4">
      <div class="card h-100 p-4">

        {% block sidebar %}
          {% include "includes/sidebar.html" %}
        {% endblock %}

      </div>
    </div>
    <div class="col-sm-10 mh-100 bg-light p-4">
      <div class="card h-100 p-4 overflow-auto">

        {% block content %}

        {% endblock %}

      </div>

      {#              {% block pagination %}#}
      {#                  {% include "includes/pagination.html" %}#}
      {#              {% endblock %}#}

    </div>
  </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>
</body>
</html>

task_manager/templates/includes/pagination.html
{% load query_transform %}

{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

task_manager/templates/includes/search.html
{% load crispy_forms_filters %}

<form method="GET" action="" class="mb-4">
  <div class="input-group">
    {{ search_form.name|as_crispy_field }}
    <div>
      <button class="btn btn-dark ms-2" type="submit">Search</button>
    </div>
  </div>
</form>

task_manager/templates/includes/sidebar.html
<a href="{% url 'task_manager:index' %}">
  <button type="button" class="btn btn-secondary mb-2 w-100">Home</button>
</a>

<a href="{% url 'task_manager:worker-list' %}">
  <button type="button" class="btn btn-secondary mb-2 w-100">All workers</button>
</a>

<a href="{% url 'task_manager:position-list' %}">
  <button type="button" class="btn btn-secondary mb-2 w-100">All positions</button>
</a>

<a href="{% url 'task_manager:task-type-list' %}">
  <button type="button" class="btn btn-secondary mb-2 w-100">All types</button>
</a>

<a href="{% url 'task_manager:task-list' %}">
  <button type="button" class="btn btn-secondary mb-2 w-100">All tasks</button>
</a>

{% if request.user.is_authenticated %}
  <div class="my-auto">
    <span class="badge rounded-pill text-bg-success w-100 mb-1 p-2">Active: {{ active_tasks }}</span>
    <span class="badge rounded-pill text-bg-danger w-100 mb-1 p-2">Waiting: {{ waiting_tasks }}</span>
    <span class="badge rounded-pill text-bg-primary w-100 mb-1 p-2">Completed: {{ completed_tasks }}</span>
  </div>
{% endif %}

<div class="mt-auto ">
  <ul class="sidebar-nav list-group mt-3 ">
    {% if user.is_authenticated %}
      <li class="list-group-item bg-light">{{ user.get_username }}</li>
      <li class="list-group-item bg-light"><a href="{% url 'logout' %}?next={{ request.path }}">Logout</a></li>
    {% else %}
      <li class="list-group-item bg-light"><a href="{% url 'login' %}?next={{ request.path }}">Login</a></li>
      <li class="list-group-item bg-light"><a href="{% url 'register' %}?next={{ request.path }}">Register</a></li>
    {% endif %}
  </ul>
</div>

task_manager/templates/index.html
{% extends "base.html" %}

{% block content %}
  <h1>Welcome to the Company Task Manager Django Project!</h1>
    <p>This powerful web application simplifies task management within your company or organization, making it easier than ever to collaborate and stay organized. Here's a brief guide on how to use it:</p>
    <p>Use login: "michael.davis" and pass: "z32=iF?9gtm@>z#" for test.</p>

    <h4>1. Registration and Login:</h4>
    <ul>
        <li>If you're a new user, start by registering an account. Click on the "Register" link or button on the homepage.</li>
        <li>Fill in the required information, such as your username, email, and password.</li>
        <li>Once registered, you can log in securely using your credentials by clicking on the "Login" link or button.</li>
    </ul>

    <h4>2. Task Creation:</h4>
    <ul>
        <li>After logging in, you can create new tasks by clicking on the "Create Task" button on tasks page.</li>
        <li>Provide details for the task, including the title, description, due date, and assignees.</li>
        <li>Click "Submit" to add it to the system.</li>
    </ul>

    <h4>3. Task Status Tracking:</h4>
    <ul>
        <li>Keep track of task statuses to monitor progress.</li>
    </ul>

    <h4>4. Task Searching:</h4>
    <ul>
        <li>Easily find specific tasks by using the search feature.</li>
        <li>Enter the task title or keywords in the search bar to locate tasks quickly.</li>
    </ul>

    <h4>5. User Management (Admins Only):</h4>
    <ul>
        <li>Administrators have additional privileges to manage user accounts and roles.</li>
        <li>Access the admin panel (superuser credentials required) to control user accounts and task types.</li>
    </ul>
{% endblock %}

task_manager/templates/position_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Position list
  </h1>

  {% if position_list %}
    <table class="table">
      <tr>
          <th>ID</th>
          <th>Position</th>
        </tr>
      {% for position in position_list %}
        <tr>
          <td>{{ position.id }}</td>
          <td>{{ position.name }}</td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
    <p>There are no positions.</p>
  {% endif %}

{% endblock %}

task_manager/templates/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

task_manager/templates/task_list.html
{% extends "base.html" %}

{% block content %}

  <div class="row">
    <div class="col">
      <a href="{% url 'task_manager:task-create' %}">
        <button type="button" class="btn btn-dark">Create task</button>
      </a>
    </div>
    <div class="col d-flex justify-content-end">
      {% include "includes/search.html" %}
    </div>
  </div>


  <div class="row row-cols-1 row-cols-md-3 g-4">
    {% if task_list %}

      {% for task in task_list %}

        <div class="col">
          <div class="card h-100 bg-light">
            <div class="card-body d-flex flex-column">

              <div class="d-flex justify-content-between mb-2">

                {% if task.is_completed %}
                  <span class="badge rounded-pill text-bg-primary">Completed</span>
                {% else %}
                  <span class="badge rounded-pill text-bg-success">Active</span>
                {% endif %}
                <span class="badge rounded-pill text-bg-secondary">{{ task.get_priority_display }}</span>
                {% if task.deadline < today %}
                  <span class="badge rounded-pill text-bg-danger">Due date: {{ task.deadline }}</span>
                {% else %}
                  <span class="badge rounded-pill text-bg-info">Due date: {{ task.deadline }}</span>
                {% endif %}

              </div>

              <h5 class="card-title">{{ task.name }}</h5>
              <p class="card-text">{{ task.description }}</p>
              <p><span class="fw-semibold">Assignor:</span> {{ task.assignor.first_name }} {{ task.assignor.last_name }}
              </p>
              <span class="fw-semibold">Assignees:</span>
              <ul>
                {% for worker in task.assignees.all %}
                  <li>{{ worker.first_name }} {{ worker.last_name }}</li>
                {% endfor %}
              </ul>

              <div class="mt-auto">
                <div class="d-flex justify-content-end mb-2">
                  <a href="{% url 'task_manager:task-update' pk=task.pk %}">
                    <span class="badge rounded-pill text-bg-dark mx-2">Edit</span>
                  </a>
                </div>
              </div>

            </div>
          </div>
        </div>

      {% endfor %}

    {% else %}

      <p>There no tasks.</p>

    {% endif %}

  </div>

{% endblock %}

task_manager/templates/task_type_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Task type list
  </h1>

  {% if tasktype_list %}
    <table class="table">
      <tr>
          <th>ID</th>
          <th>Task type</th>
        </tr>
      {% for task_type in tasktype_list %}
        <tr>
          <td>{{ task_type.id }}</td>
          <td>{{ task_type.name }}</td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
    <p>There are no task types.</p>
  {% endif %}

{% endblock %}

task_manager/templates/worker_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Worker list
  </h1>
  {% if worker_list %}
    <table class="table">
      <tr>
          <th>ID</th>
          <th>Username</th>
          <th>First name</th>
          <th>Last name</th>
          <th>Position</th>
        </tr>
      {% for worker in worker_list %}
        <tr>
          <td>{{ worker.id }}</td>
          <td>{{ worker.username }}</td>
          <td>{{ worker.first_name }}</td>
          <td>{{ worker.last_name }}</td>
          <td>{{ worker.position }}</td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
    <p>There are no workers.</p>
  {% endif %}

{% endblock %}